# "~/.config/nvim/stylua.toml"
syntax = "Lua51"
indent_type = "Spaces"
indent_width = 2
column_width = 120
quote_style = "AutoPreferDouble"
line_endings = "Unix"
call_parentheses = "None"
[sort_requires]
enabled = true
